# Generated by Django 3.1.1 on 2020-11-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image', models.ImageField(upload_to='event_images/')),
                ('title', models.CharField(max_length=300)),
                ('data', models.DateTimeField()),
                ('text', models.TextField()),
            ],
        ),
    ]
